language: python
cache:
  - pip
matrix:
  include:
    - os: linux
      python: 2.7
      env: TOXENV=py27
    - os: osx
      language: generic
      env: TOXENV=py27
install:
  - ./.travis/install.sh

script:
  - py.test --cov=WonderPy_Node -v test
  - coverage xml
  - python-codacy-coverage -r coverage.xml
